// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wvkmagueziiglyjplrsd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Ind2a21hZ3VlemlpZ2x5anBscnNkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjAxMDMzMjAsImV4cCI6MjA3NTY3OTMyMH0.0JcrqmxPY3N7hs8CwOFK-j-Lbsm9oIoyVcMeBViBQjA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});